agent_params_loader:
   ros__parameters:
       sampling_time: 0.033
       runge_kutta_45: True
       ground_height: -0.1
       robot_control: True
       robot_name: "pioneer3at"
       laser_sensor_name: "laser"
       robot_radius: 0.3
       robot_mass: 35
       robot_velocity: 0.9
       robot_relaxation_time: 0.5
       robot_k_orthogonal: 1.0
       robot_k_damping: 500.0
       robot_k_lambda: 0.3
       robot_alpha: 3.0
       robot_Ai: 2000.0
       robot_Aw: 2000.0
       robot_Bi: 0.08
       robot_Bw: 0.08
       robot_k1: 120000.0
       robot_k2: 240000.0
       robot_initial_orientation: -180.0
       robot_waypoints: [-6.5,-0.0,6.5,0.0]
       robot_initial_position: [6.5,0.0]
       robot_ignore_obstacles: ["circular_workspace"]
       attach_cylinder_to_humans: True
       consider_robot: True
       agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7","agent8","agent9","agent10","agent11","agent12","agent13","agent14","agent15","agent16","agent17","agent18","agent19","agent20","agent21"]
       agent1:
           waypoints: [-1.3943,6.3487,1.3943,-6.3487]
           initial_orientation: 102.3863
           initial_position: [1.3943,-6.3487]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent2:
           waypoints: [-6.3513,-1.3822,6.3513,1.3822]
           initial_orientation: -167.7223
           initial_position: [6.3513,1.3822]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent3:
           waypoints: [3.8868,5.2099,-3.8868,-5.2099]
           initial_orientation: 53.2757
           initial_position: [-3.8868,-5.2099]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent4:
           waypoints: [-3.1127,-5.7063,3.1127,5.7063]
           initial_orientation: -118.6117
           initial_position: [3.1127,5.7063]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent5:
           waypoints: [4.6006,-4.5918,-4.6006,4.5918]
           initial_orientation: -44.9457
           initial_position: [-4.6006,4.5918]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent6:
           waypoints: [-5.9121,-2.7012,5.9121,2.7012]
           initial_orientation: -155.4447
           initial_position: [5.9121,2.7012]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent7:
           waypoints: [-2.7124,5.907,2.7124,-5.907]
           initial_orientation: 114.664
           initial_position: [2.7124,-5.907]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent8:
           waypoints: [6.435,-0.9173,-6.435,0.9173]
           initial_orientation: -8.1127
           initial_position: [-6.435,0.9173]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent9:
           waypoints: [-6.2411,1.8162,6.2411,-1.8162]
           initial_orientation: 163.7747
           initial_position: [6.2411,-1.8162]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent10:
           waypoints: [-4.2549,-4.9138,4.2549,4.9138]
           initial_orientation: -130.8893
           initial_position: [4.2549,4.9138]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent11:
           waypoints: [2.2762,-6.0884,-2.2762,6.0884]
           initial_orientation: -69.501
           initial_position: [-2.2762,6.0884]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent12:
           waypoints: [5.7003,3.1235,-5.7003,-3.1235]
           initial_orientation: 28.7203
           initial_position: [-5.7003,-3.1235]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent13:
           waypoints: [4.9058,4.2642,-4.9058,-4.2642]
           initial_orientation: 40.998
           initial_position: [-4.9058,-4.2642]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent14:
           waypoints: [-4.9219,4.2456,4.9219,-4.2456]
           initial_orientation: 139.2193
           initial_position: [4.9219,-4.2456]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent15:
           waypoints: [-3.9065,5.1951,3.9065,-5.1951]
           initial_orientation: 126.9417
           initial_position: [3.9065,-5.1951]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent16:
           waypoints: [-0.0123,6.5,0.0123,-6.5]
           initial_orientation: 90.1087
           initial_position: [0.0123,-6.5]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent17:
           waypoints: [6.0927,-2.2647,-6.0927,2.2647]
           initial_orientation: -20.3903
           initial_position: [-6.0927,2.2647]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent18:
           waypoints: [-1.828,-6.2377,1.828,6.2377]
           initial_orientation: -106.334
           initial_position: [1.828,6.2377]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent19:
           waypoints: [-0.4598,-6.4837,0.4598,6.4837]
           initial_orientation: -94.0563
           initial_position: [0.4598,6.4837]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent20:
           waypoints: [5.4718,-3.5085,-5.4718,3.5085]
           initial_orientation: -32.668
           initial_position: [-5.4718,3.5085]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent21:
           waypoints: [6.2342,1.8399,-6.2342,-1.8399]
           initial_orientation: 16.4427
           initial_position: [-6.2342,-1.8399]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
