agent_params_loader:
   ros__parameters:
       sampling_time: 0.033
       runge_kutta_45: True
       ground_height: -0.1
       robot_control: True
       robot_name: "pioneer3at"
       laser_sensor_name: "laser"
       robot_radius: 0.3
       robot_mass: 35
       robot_goal_weight: 2.0
       robot_obstacle_weight: 10.0
       robot_social_weight: 15.0
       robot_velocity: 0.9
       robot_initial_orientation: -3.1416
       robot_waypoints: [-6.5,-0.0,6.5,0.0]
       robot_initial_position: [6.5,0.0]
       robot_ignore_obstacles: ["circular_workspace"]
       attach_cylinder_to_humans: True
       consider_robot: True
       agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7","agent8","agent9","agent10","agent11","agent12","agent13","agent14","agent15","agent16","agent17","agent18","agent19","agent20","agent21","agent22","agent23","agent24","agent25","agent26","agent27","agent28"]
       agent1:
           waypoints: [-6.348,-1.3973,6.348,1.3973]
           initial_orientation: -2.9249
           initial_position: [6.348,1.3973]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent2:
           waypoints: [-5.8992,-2.7293,5.8992,2.7293]
           initial_orientation: -2.7083
           initial_position: [5.8992,2.7293]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent3:
           waypoints: [-5.1746,-3.9336,5.1746,3.9336]
           initial_orientation: -2.4916
           initial_position: [5.1746,3.9336]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent4:
           waypoints: [-4.208,-4.9541,4.208,4.9541]
           initial_orientation: -2.2749
           initial_position: [4.208,4.9541]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent5:
           waypoints: [-3.0447,-5.7428,3.0447,5.7428]
           initial_orientation: -2.0583
           initial_position: [3.0447,5.7428]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent6:
           waypoints: [-1.7389,-6.2631,1.7389,6.2631]
           initial_orientation: -1.8416
           initial_position: [1.7389,6.2631]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent7:
           waypoints: [-0.3519,-6.4905,0.3519,6.4905]
           initial_orientation: -1.625
           initial_position: [0.3519,6.4905]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent8:
           waypoints: [1.0516,-6.4144,-1.0516,6.4144]
           initial_orientation: -1.4083
           initial_position: [-1.0516,6.4144]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent9:
           waypoints: [2.4059,-6.0383,-2.4059,6.0383]
           initial_orientation: -1.1916
           initial_position: [-2.4059,6.0383]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent10:
           waypoints: [3.6477,-5.38,-3.6477,5.38]
           initial_orientation: -0.975
           initial_position: [-3.6477,5.38]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent11:
           waypoints: [4.719,-4.47,-4.719,4.47]
           initial_orientation: -0.7583
           initial_position: [-4.719,4.47]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent12:
           waypoints: [5.5696,-3.3511,-5.5696,3.3511]
           initial_orientation: -0.5417
           initial_position: [-5.5696,3.3511]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent13:
           waypoints: [6.1597,-2.0755,-6.1597,2.0755]
           initial_orientation: -0.325
           initial_position: [-6.1597,2.0755]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent14:
           waypoints: [6.4619,-0.7028,-6.4619,0.7028]
           initial_orientation: -0.1083
           initial_position: [-6.4619,0.7028]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent15:
           waypoints: [6.4619,0.7028,-6.4619,-0.7028]
           initial_orientation: 0.1083
           initial_position: [-6.4619,-0.7028]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent16:
           waypoints: [6.1597,2.0755,-6.1597,-2.0755]
           initial_orientation: 0.325
           initial_position: [-6.1597,-2.0755]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent17:
           waypoints: [5.5696,3.3511,-5.5696,-3.3511]
           initial_orientation: 0.5417
           initial_position: [-5.5696,-3.3511]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent18:
           waypoints: [4.719,4.47,-4.719,-4.47]
           initial_orientation: 0.7583
           initial_position: [-4.719,-4.47]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent19:
           waypoints: [3.6477,5.38,-3.6477,-5.38]
           initial_orientation: 0.975
           initial_position: [-3.6477,-5.38]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent20:
           waypoints: [2.4059,6.0383,-2.4059,-6.0383]
           initial_orientation: 1.1916
           initial_position: [-2.4059,-6.0383]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent21:
           waypoints: [1.0516,6.4144,-1.0516,-6.4144]
           initial_orientation: 1.4083
           initial_position: [-1.0516,-6.4144]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent22:
           waypoints: [-0.3519,6.4905,0.3519,-6.4905]
           initial_orientation: 1.625
           initial_position: [0.3519,-6.4905]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent23:
           waypoints: [-1.7389,6.2631,1.7389,-6.2631]
           initial_orientation: 1.8416
           initial_position: [1.7389,-6.2631]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent24:
           waypoints: [-3.0447,5.7428,3.0447,-5.7428]
           initial_orientation: 2.0583
           initial_position: [3.0447,-5.7428]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent25:
           waypoints: [-4.208,4.9541,4.208,-4.9541]
           initial_orientation: 2.2749
           initial_position: [4.208,-4.9541]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent26:
           waypoints: [-5.1746,3.9336,5.1746,-3.9336]
           initial_orientation: 2.4916
           initial_position: [5.1746,-3.9336]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent27:
           waypoints: [-5.8992,2.7293,5.8992,-2.7293]
           initial_orientation: 2.7083
           initial_position: [5.8992,-2.7293]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent28:
           waypoints: [-6.348,1.3973,6.348,-1.3973]
           initial_orientation: 2.9249
           initial_position: [6.348,-1.3973]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
