agent_params_loader:
   ros__parameters:
       sampling_time: 0.033
       runge_kutta_45: True
       ground_height: -0.1
       robot_control: True
       robot_name: "pioneer3at"
       laser_sensor_name: "laser"
       robot_radius: 0.3
       robot_mass: 35
       robot_velocity: 0.9
       robot_relaxation_time: 0.5
       robot_k_orthogonal: 1.0
       robot_k_damping: 500.0
       robot_k_lambda: 0.3
       robot_alpha: 3.0
       robot_Ai: 2000.0
       robot_Aw: 2000.0
       robot_Bi: 0.08
       robot_Bw: 0.08
       robot_k1: 120000.0
       robot_k2: 240000.0
       robot_initial_orientation: -180.0
       robot_waypoints: [-6.5,-0.0,6.5,0.0]
       robot_initial_position: [6.5,0.0]
       robot_ignore_obstacles: ["circular_workspace"]
       attach_cylinder_to_humans: True
       consider_robot: True
       agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7","agent8","agent9","agent10","agent11","agent12","agent13","agent14"]
       agent1:
           waypoints: [-5.938,-2.6438,5.938,2.6438]
           initial_orientation: -156.0
           initial_position: [5.938,2.6438]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent2:
           waypoints: [-4.3493,-4.8304,4.3493,4.8304]
           initial_orientation: -132.0
           initial_position: [4.3493,4.8304]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent3:
           waypoints: [-2.0086,-6.1819,2.0086,6.1819]
           initial_orientation: -108.0
           initial_position: [2.0086,6.1819]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent4:
           waypoints: [0.6794,-6.4644,-0.6794,6.4644]
           initial_orientation: -84.0
           initial_position: [-0.6794,6.4644]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent5:
           waypoints: [3.25,-5.6292,-3.25,5.6292]
           initial_orientation: -60.0
           initial_position: [-3.25,5.6292]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent6:
           waypoints: [5.2586,-3.8206,-5.2586,3.8206]
           initial_orientation: -36.0
           initial_position: [-5.2586,3.8206]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent7:
           waypoints: [6.358,-1.3514,-6.358,1.3514]
           initial_orientation: -12.0
           initial_position: [-6.358,1.3514]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent8:
           waypoints: [6.358,1.3514,-6.358,-1.3514]
           initial_orientation: 12.0
           initial_position: [-6.358,-1.3514]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent9:
           waypoints: [5.2586,3.8206,-5.2586,-3.8206]
           initial_orientation: 36.0
           initial_position: [-5.2586,-3.8206]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent10:
           waypoints: [3.25,5.6292,-3.25,-5.6292]
           initial_orientation: 60.0
           initial_position: [-3.25,-5.6292]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent11:
           waypoints: [0.6794,6.4644,-0.6794,-6.4644]
           initial_orientation: 84.0
           initial_position: [-0.6794,-6.4644]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent12:
           waypoints: [-2.0086,6.1819,2.0086,-6.1819]
           initial_orientation: 108.0
           initial_position: [2.0086,-6.1819]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent13:
           waypoints: [-4.3493,4.8304,4.3493,-4.8304]
           initial_orientation: 132.0
           initial_position: [4.3493,-4.8304]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent14:
           waypoints: [-5.938,2.6438,5.938,-2.6438]
           initial_orientation: 156.0
           initial_position: [5.938,-2.6438]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
