agent_params_loader:
   ros__parameters:
       sampling_time: 0.033
       runge_kutta_45: True
       ground_height: -0.1
       robot_control: True
       robot_name: "pioneer3at"
       laser_sensor_name: "laser"
       robot_radius: 0.3
       robot_mass: 35
       robot_goal_weight: 2.0
       robot_obstacle_weight: 10.0
       robot_social_weight: 15.0
       robot_velocity: 0.9
       robot_initial_orientation: -180.0
       robot_waypoints: [-6.5,-0.0,6.5,0.0]
       robot_initial_position: [6.5,0.0]
       robot_ignore_obstacles: ["circular_workspace"]
       attach_cylinder_to_humans: True
       consider_robot: True
       agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7","agent8","agent9","agent10","agent11","agent12","agent13","agent14","agent15","agent16","agent17","agent18","agent19","agent20","agent21"]
       agent1:
           waypoints: [-6.2367,-1.8313,6.2367,1.8313]
           initial_orientation: -163.6364
           initial_position: [6.2367,1.8313]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent2:
           waypoints: [-5.4681,-3.5142,5.4681,3.5142]
           initial_orientation: -147.2727
           initial_position: [5.4681,3.5142]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent3:
           waypoints: [-4.2566,-4.9124,4.2566,4.9124]
           initial_orientation: -130.9091
           initial_position: [4.2566,4.9124]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent4:
           waypoints: [-2.7002,-5.9126,2.7002,5.9126]
           initial_orientation: -114.5455
           initial_position: [2.7002,5.9126]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent5:
           waypoints: [-0.925,-6.4338,0.925,6.4338]
           initial_orientation: -98.1818
           initial_position: [0.925,6.4338]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent6:
           waypoints: [0.925,-6.4338,-0.925,6.4338]
           initial_orientation: -81.8182
           initial_position: [-0.925,6.4338]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent7:
           waypoints: [2.7002,-5.9126,-2.7002,5.9126]
           initial_orientation: -65.4545
           initial_position: [-2.7002,5.9126]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent8:
           waypoints: [4.2566,-4.9124,-4.2566,4.9124]
           initial_orientation: -49.0909
           initial_position: [-4.2566,4.9124]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent9:
           waypoints: [5.4681,-3.5142,-5.4681,3.5142]
           initial_orientation: -32.7273
           initial_position: [-5.4681,3.5142]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent10:
           waypoints: [6.2367,-1.8313,-6.2367,1.8313]
           initial_orientation: -16.3636
           initial_position: [-6.2367,1.8313]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent11:
           waypoints: [6.5,-0.0,-6.5,0.0]
           initial_orientation: 0.0
           initial_position: [-6.5,0.0]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent12:
           waypoints: [6.2367,1.8313,-6.2367,-1.8313]
           initial_orientation: 16.3636
           initial_position: [-6.2367,-1.8313]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent13:
           waypoints: [5.4681,3.5142,-5.4681,-3.5142]
           initial_orientation: 32.7273
           initial_position: [-5.4681,-3.5142]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent14:
           waypoints: [4.2566,4.9124,-4.2566,-4.9124]
           initial_orientation: 49.0909
           initial_position: [-4.2566,-4.9124]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent15:
           waypoints: [2.7002,5.9126,-2.7002,-5.9126]
           initial_orientation: 65.4545
           initial_position: [-2.7002,-5.9126]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent16:
           waypoints: [0.925,6.4338,-0.925,-6.4338]
           initial_orientation: 81.8182
           initial_position: [-0.925,-6.4338]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent17:
           waypoints: [-0.925,6.4338,0.925,-6.4338]
           initial_orientation: 98.1818
           initial_position: [0.925,-6.4338]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent18:
           waypoints: [-2.7002,5.9126,2.7002,-5.9126]
           initial_orientation: 114.5455
           initial_position: [2.7002,-5.9126]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent19:
           waypoints: [-4.2566,4.9124,4.2566,-4.9124]
           initial_orientation: 130.9091
           initial_position: [4.2566,-4.9124]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent20:
           waypoints: [-5.4681,3.5142,5.4681,-3.5142]
           initial_orientation: 147.2727
           initial_position: [5.4681,-3.5142]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent21:
           waypoints: [-6.2367,1.8313,6.2367,-1.8313]
           initial_orientation: 163.6364
           initial_position: [6.2367,-1.8313]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
