agent_params_loader:
  ros__parameters:
    # GLOBAL PARAMETERS
    sampling_time: 0.033
    runge_kutta_45: True
    ground_height: -0.1
    robot_control: True
    robot_name: "pioneer3at"
    laser_sensor_name: "laser"
    robot_initial_orientation: -90.0
    robot_waypoints: [0.0,-6.0,0.0,6.0]
    robot_initial_position: [0.0,6.0]
    robot_radius: 0.3
    robot_mass: 35
    robot_goal_weight: 2.0
    robot_obstacle_weight: 10.0
    robot_social_weight: 15.0
    robot_velocity: 0.9
    robot_ignore_obstacles: ["circular_workspace"]
    agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7","agent8","agent9","agent10","agent11","agent12","agent13","agent14"] 
    attach_cylinder_to_humans: True
    consider_robot: True
    # ACTORS PARAMETERS
    agent1:
      waypoints: [-2.4404,-5.4813,2.4404,5.4813] 
      initial_orientation: -114.0
      initial_position: [2.4404,5.4813] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent2:
      waypoints: [-4.4588,-4.0147,4.4588,4.0147] 
      initial_orientation: -138.0 
      initial_position: [4.4588,4.0147] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent3:
      waypoints: [-5.7063,-1.8541,5.7063,1.8541] 
      initial_orientation: -162.0
      initial_position: [5.7063,1.8541] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent4:
      waypoints: [-5.9671,0.6271,5.9671,-0.6271] 
      initial_orientation: 174.0
      initial_position: [5.9671,-0.6271] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent5:
      waypoints: [-5.1961,3.0,5.1961,-3.0] 
      initial_orientation: 150.0
      initial_position: [5.1961,-3.0]
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent6:
      waypoints: [-3.5267,4.8541,3.5267,-4.8541] 
      initial_orientation: 126.0 
      initial_position: [3.5267,-4.8541] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent7:
      waypoints: [-1.2474,5.8688,1.2474,-5.8688] 
      initial_orientation: 102.0
      initial_position: [1.2474,-5.8688] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent8:
      waypoints: [1.2474,5.8688,-1.2474,-5.8688] 
      initial_orientation: 78.0
      initial_position: [-1.2474,-5.8688] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent9:
      waypoints: [3.5267,4.8541,-3.5267,-4.8541] 
      initial_orientation: 54.0 
      initial_position: [-3.5267,-4.8541] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent10:
      waypoints: [5.1961,3.0,-5.1961,-3.0] 
      initial_orientation: 30.0
      initial_position: [-5.1961,-3.0] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent11:
      waypoints: [5.9671,0.6271,-5.9671,-0.6271] 
      initial_orientation: 6.0 
      initial_position: [-5.9671,-0.6271] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent12:
      waypoints: [5.7063,-1.8541,-5.7063,1.8541] 
      initial_orientation: -18.0
      initial_position: [-5.7063,1.8541]
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent13:
      waypoints: [4.4588,-4.0147,-4.4588,4.0147] 
      initial_orientation: -42.0
      initial_position: [-4.4588,4.0147] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent14:
      waypoints: [2.4404,-5.4812,-2.4404,5.4812] 
      initial_orientation: -66.0
      initial_position: [-2.4404,5.4812] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False